app/models/__init__.py
from .user import User

app/models/user.py
from app import db
from flask_login import UserMixin


class User(UserMixin, db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(32), nullable=False, unique=True)
    name = db.Column(db.String(32), nullable=False, unique=True)
    password = db.Column(db.String(128), nullable=False)
    is_super_user = db.Column(db.Boolean(), default=False)

    def __repr__(self):
        return '%r' % self.name

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_ckeditor import CKEditor
from flask_login import LoginManager
from flask_cors import CORS
from apispec.ext.marshmallow import MarshmallowPlugin
from apispec import APISpec
from flask_apispec.extension import FlaskApiSpec
from app.settings import Config

cors = CORS()
bootstrap = Bootstrap()
db = SQLAlchemy()
ckeditor = CKEditor()


def create_app(config_object=Config):
    app = Flask(__name__)
    app.config.from_object(config_object)

    db.init_app(app)

    bootstrap.init_app(app)
    if app.config['CORS_ON']:
        cors.init_app(app)
    ckeditor.init_app(app)
    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    from .models import User

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

    docs = FlaskApiSpec()

    docs.init_app(app)

    app.config.update({
        'APISPEC_SPEC': APISpec(
            title='some_title',
            version='v1',
            openapi_version='2.0',
            plugins=[MarshmallowPlugin()],
        ),
        'APISPEC_SWAGGER_URL': '/swagger/'
    })

    # blueprint for non-auth parts of app
    from .views import homepage as homepage_blueprint
    app.register_blueprint(homepage_blueprint)

    # blueprint for non-auth parts of app
    from .views import profile as profile_blueprint
    app.register_blueprint(profile_blueprint)

    # blueprint for auth routes in our app
    from .views import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

    return app

app/views/__init__.py
from .homepage import homepage
from .profile import profile
from .auth import auth

app/views/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_user, logout_user, login_required
from werkzeug.security import generate_password_hash, check_password_hash
from .. import db
from ..models import User

auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():

    if request.method == 'GET':
        return render_template('login.html')

    elif request.method == 'POST':

        email = request.form.get('email')
        password = request.form.get('password')
        remember = True if request.form.get('remember') else False
        user = User.query.filter_by(email=email).first()

        if not user or not check_password_hash(user.password, password):
            flash('Wrong password or email.')
            return redirect(url_for('auth.login'))

        login_user(user, remember=remember)
        return redirect(url_for('profile.index'))


@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'GET':
        return render_template('signup.html')
    elif request.method == 'POST':
        data = {
            'email': request.form.get('email'),
            'name': request.form.get('name'),
            'password': request.form.get('password'),
            'is_super_user': request.form.get('is_super_user'),
        }

        is_not_valid = validator(email=request.form.get('email'), name=request.form.get('name'))

        if is_not_valid:
            flash(is_not_valid)
            return redirect(url_for('auth.signup'))

        data['password'] = generate_password_hash(request.form.get('password'), method='sha256')
        user = User(**data)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('auth.login'))


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('homepage.index'))


def validator(name, email):
    if User.query.filter_by(email=email).first():
        return 'User with same email already created'
    elif User.query.filter_by(name=name).first():
        return 'User with same username already created'
    else:
        return False

app/views/homepage.py
from flask import Blueprint, render_template

homepage = Blueprint('homepage', __name__)


@homepage.route('/')
def index():
    return render_template('index.html')

app/views/profile.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user
from .. import db
from ..models import User
from .auth import validator

profile = Blueprint('profile', __name__)


@profile.route('/profile', methods=['GET'])
@login_required
def index():
    if request.method == 'GET':
        users_to_edit = []
        if current_user.is_super_user:
            users_to_edit = User.query.filter_by(is_super_user=False).all()
        else:
            users_to_edit.append(current_user)

        return render_template('profile.html', name=current_user.name, users_to_edit=users_to_edit)


@profile.route('/profile/<name>', methods=['POST'])
@login_required
def detail_profile(name):
    if current_user.is_super_user or current_user.name == name and request.method == 'POST':
        data = {
            'email': request.form.get('email'),
            'name': request.form.get('name'),
            'password': request.form.get('password'),
            'is_super_user': request.form.get('is_super_user')
        }

        is_not_valid = validator(name=request.form.get('name'),
                                 email=request.form.get('email'))
        if is_not_valid:
            flash(is_not_valid)
            return redirect(url_for('profile.index'))

        User.query.filter_by(name=name).update(**data)
        db.session.commit()
        flash('User edited successfully')
        return redirect(url_for('profile.index'))


@profile.route('/delete_user/<name>', methods=['DELETE'])
@login_required
def delete_user(name):
    user = User.query.filter_by(name=name).first()
    db.session.delete(user)
    return redirect(url_for('profile.index'))

app/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Flask Auth Example</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
</head>

<body>
    <section class="hero is-primary is-fullheight">

        <div class="hero-head">
            <nav class="navbar">
                <div class="container">

                    <div id="navbarMenuHeroA" class="navbar-menu">
                        <div class="navbar-end">
                            <a href="{{ url_for('homepage.index') }}" class="navbar-item">
                                Home
                            </a>
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('profile.index') }}" class="navbar-item">
                                Profile
                            </a>
                            {% endif %}
                            {% if not current_user.is_authenticated %}
                            <a href="{{ url_for('auth.login') }}" class="navbar-item">
                                Login
                            </a>
                            <a href="{{ url_for('auth.signup') }}" class="navbar-item">
                                Sign Up
                            </a>
                            {% endif %}
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('auth.logout') }}" class="navbar-item">
                                Logout
                            </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>
        </div>

        <div class="hero-body">
            <div class="container has-text-centered">
               {% block content %}
               {% endblock %}
            </div>
        </div>
    </section>
</body>

</html>

app/templates/index.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">
  Flask Login Example
</h1>
<h2 class="subtitle">
  Easy authentication and authorization in Flask.
</h2>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Login</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }}
            </div>
        {% endif %}
        {% endwith %}
        <form method="POST" action="/login">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="Your Email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Your Password">
                </div>
            </div>
            <div class="field">
                <label class="checkbox">
                    <input type="checkbox">
                    Remember me
                </label>
            </div>
            <button class="button is-block is-info is-large is-fullwidth">Login</button>
        </form>
    </div>
</div>
{% endblock %}

app/templates/profile.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">
  Welcome, {{ name }}!
</h1>
{% endblock %}

app/templates/signup.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Sign Up</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }}. Go to <a href="{{ url_for('auth.login') }}">login page</a>.
            </div>
        {% endif %}
        {% endwith %}
        <form method="POST" action="/signup">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="Email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="name" placeholder="Name" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Password">
                </div>
            </div>

            <button class="button is-block is-info is-large is-fullwidth">Sign Up</button>
        </form>
    </div>
</div>
{% endblock %}